[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# These are default security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "frame-ancestors 'none'"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Handle 404 errors with a custom page
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Force trailing slash which helps with Next.js routing
[[redirects]]
  from = "/*"
  to = "/:splat/"
  status = 301
  force = false
  conditions = {Path = {ends_with = ""}}

# Handle Next.js static assets
[[redirects]]
  from = "/_next/static/*"
  to = "/static/:splat"
  status = 200

# Handle Next.js API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/nextjs-api/:splat"
  status = 200

# Catch all for Next.js routes - IMPORTANT
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/nextjs"
  status = 200
  force = false 