[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

# This is the recommended way to use Next.js with Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"

# These are default security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "frame-ancestors 'none'"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Add cache control for static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Handle 404 errors with a custom page
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Force trailing slash which helps with Next.js routing
[[redirects]]
  from = "/*"
  to = "/:splat/"
  status = 301
  force = false
  conditions = {Path = {ends_with = ""}}

# Handle Next.js static assets
[[redirects]]
  from = "/_next/static/*"
  to = "/static/:splat"
  status = 200

# Handle Next.js API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/nextjs-api/:splat"
  status = 200

# Handle Next.js image optimization
[[redirects]]
  from = "/_next/image/"
  query = {url = ":url", w = ":width", q = ":quality"}
  to = "/.netlify/images?url=:url&w=:width&q=:quality"
  status = 200

# Catch all for Next.js routes - IMPORTANT
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/nextjs"
  status = 200
  force = false 