[build]
  command = "bash fix-react-types.sh && npm run netlify-build"
  publish = ".next"
  functions = "netlify/functions"

# This is the recommended way to use Next.js with Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"
  
# Exclude unnecessary files from function bundling
[functions]
  # Exclude any unnecessary files from being included in the function bundle
  included_files = ["!node_modules/**, !.next/cache/**"]
  # Use node18 for better performance
  node_bundler = "esbuild"
  # Optimize function size
  external_node_modules = ["@supabase/supabase-js"]

# These are default security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "frame-ancestors 'none'; default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://txndzhjxsijyjeuoqfxl.supabase.co https://*.supabase.co;"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Add cache control for static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Handle 404 errors with a custom page
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Catch all for Next.js routes
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/nextjs"
  status = 200
  force = false

# Force trailing slash which helps with Next.js routing
[[redirects]]
  from = "/*"
  to = "/:splat/"
  status = 301
  force = false
  conditions = {Path = {ends_with = ""}}

# Handle Next.js static assets
[[redirects]]
  from = "/_next/static/*"
  to = "/static/:splat"
  status = 200

# Handle Next.js API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/nextjs-api/:splat"
  status = 200

# Handle Next.js image optimization
[[redirects]]
  from = "/_next/image/"
  query = {url = ":url", w = ":width", q = ":quality"}
  to = "/.netlify/images?url=:url&w=:width&q=:quality"
  status = 200

# Add build caching
[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NEXT_USE_NETLIFY_EDGE = "1"
  NEXT_PRIVATE_TARGET = "server"
  NEXT_SHARP_PATH = "/opt/buildhome/.netlify/plugins/node_modules/sharp" 